### ISSUE TITLE
Implement 'click' functionality

### ISSUE THREAD

**Issue by mattdy** [mattdy/python-lis3dh#2]
The LIS3DH allows for the 'interrupt' (INT) pin to be set high according to a set of given parameters, functionality to set and make use of this is not currently exposed in this library.

[Example C code here](https://github.com/adafruit/Adafruit_LIS3DH/blob/master/Adafruit_LIS3DH.cpp#L209)

**Comment by MalSmalley** [comment]
Nice Driver function.
I've found one error (RANGE_16 divisor should be 1365.33 not 2048)
But also implemented Click functionality via INT 
please add me as a collaborator & I'll upload a branch with the changes

**Comment by mattdy** [comment]
Thanks @MalSmalley - please submit a PR and I'll happily merge the changes!
